# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
